server:
  port: 8081
spring:
  application:
    name: MassSelection
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.138.199.12:13306/ms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  redis:
    host: 43.138.199.12
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.ms.entity # 别名扫描包
logging:
  level:
    com.ms: debug
  pattern:
    dateformat: mm:ss.SSS